### PR TITLE
docs(run): fix run helloworld instructions

### PR DESCRIPTION
**Pull request by grant**
Fixes cd path for sample to work properly.

Fixes https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1204

### CODE REVIEW

**Review by grayside — COMMENTED** [review]
Per request from @bshaffer this command assumes a starting working directory of the directory from where you would have run git clone. I have no opinion either way.

**Comment by grant** [comment]
Thanks for the background.

IMO we should please state that assumption then. Or state the `cd` right after the `git clone` step.

If a user is linked to this README, the instructions will not work. Usually READMEs are self-isolated and expect you run commands from the directory you're reading the README in.

**Comment by bshaffer** [comment]
@grant If we include instructions on cloning the repo, we include instructions on changing directory into the repo. This is consistent with all of our tutorials.

If you'd like, split up `cd php-docs-samples/run` into the previous step where the repo is cloned. This should be clear to everyone.

**Comment by grant** [comment]
> If you'd like, split up `cd php-docs-samples/run` into the previous step where the repo is cloned. This should be clear to everyone.

Yeah, that's what I'd suggest.

**Comment by bshaffer** [comment]
This looks good but you'll need to merge master for it to pass the tests

**Review by bshaffer — APPROVED** [review]

**Comment by grant** [comment]
Sure. Rebased.

**Pull request merged**
