### PR TITLE
chore(appengine): enable deployment tests for php74

### PR DESCRIPTION
**Pull request by ace-n**
Addresses b/173545239

### CODE REVIEW

**Review by engelke — APPROVED** [review]
LGTM

**Comment by ace-n** [comment]
The PHP 7 GAE samples are in a `php72` directory.

Should we move them to a `php74` directory, or just a `php7` one? (The latter might reduce further docs moves.)

**Comment by engelke** [comment]
Assuming that PHP 7.4 samples would be very close to PHP 7.2 ones, then, yes, I would change the name of the php72 directory to php7 and update the sample to 7.4. That's what I did with the Python samples, which used to have a standard_python37 directory and now has only a standard_python3 one.

**Comment by ace-n** [comment]
@engelke gotcha. If @bshaffer is on board, I can do that in this PR + take care of the docs impact.

**Comment by bshaffer** [comment]
No tests were run by this PR, because it didn't have the `kokoro:run-all` label.

**Comment by ace-n** [comment]
Looks like the following directories were missed in #1275; fixed in #1281.
```
appengine/flexible/supervisord/addition
appengine/flexible/supervisord/replacement

**Comment by ace-n** [comment]
This is **quasi-blocked** on us cleaning up the Kokoro architecture.

**Comment by ace-n** [comment]
This PR has been obviated by #1336 and #1365.

**Pull request closed without merging**
