### PR TITLE
Speech: Print out all results.

### PR DESCRIPTION
**Pull request by jerjou**
There was some confusion where folks thought the API was only transcribing the first portion of the audio, when in fact it was because they were only using the first result. I'm updating the samples to try to reduce that confusion. See b/64934785

### CODE REVIEW

**Comment by jerjou** [comment]
Test failures look unrelated to this PR, and I'm having trouble running them manually (it skips 3/9, and tells me to `pecl install grpc`, which I did but it didn't help)

**Comment by bshaffer** [comment]
Thanks for the feedback, you also will need to enable grpc by adding `extension=grpc.so` to your `php.ini` file (which you can get by running `php -i | grep ini`). We will make the error message better!

**Comment by jerjou** [comment]
Ah - that fixed it. Okay - confirmed that all the tests pass.

**Comment by jerjou** [comment]
@bshaffer  ping? I've updated all the other language samples, and just waiting on this one so I can refresh the doc pages.

**Comment by jerjou** [comment]
Yay! Would you mind merging? I don't appear to have permissions to..

**Comment by tmatsuo** [comment]
Thanks @jerjou !

**Pull request merged**
