### PR TITLE
Updated region tags for docs

### PR DESCRIPTION
**Pull request by WalterHub**
To enable doc build

### CODE REVIEW

**Comment by tmatsuo** [comment]
I'm just curious. Why the previous tags didn't work?

**Comment by WalterHub** [comment]
For each snippets section in the docs, the topics use only a single tag, regardless of programming language. If a specific region tag isn't found in a new set of snippets, the doc won't build.

**Comment by tmatsuo** [comment]
The test is failing, but I'm pretty sure it's because the test can not handle the PR from other repos. Merging and will fix it later.

**Comment by bshaffer** [comment]
@WalterHub is this a new requirement? I have not heard of this before.

**Comment by WalterHub** [comment]
It's been used by Datastore since late 2015.

**Pull request merged**
