### PR TITLE
Fixing the broken test

### PR DESCRIPTION
**Pull request by tmatsuo**
Adding python-ipaddr for fixing the test failure

### CODE REVIEW

**Comment by tmatsuo** [comment]
The original failure has gone!

However, now the test is failing on other location:

```
running phpunit in appengine/standard/mailjet
+'[' -f vendor/bin/phpunit ']'
+vendor/bin/phpunit
PHPUnit 5.7.19 by Sebastian Bergmann and contributors.
.F                                                                  2 / 2 (100%)
Time: 1.01 seconds, Memory: 12.50MB
There was 1 failure:
1) LocalTest::testSendEmail
Failed asserting that 'Error: 401' contains ""Sent"".
```

**Comment by tmatsuo** [comment]
My guess is mailjet API key is expired, or sth

**Comment by tmatsuo** [comment]
From the history, @bshaffer added mailjet samples. He might know the secret.

**Comment by tmatsuo** [comment]
I thought about the secret.

Now all the secrets are stored in the Travis UI.
I think it's better to use more portable way to store the secret.

I'm thinking to use Cloud KMS.

1. Create a file that export the secret.
export-secrets.sh
```
#!/bin/bash
export MAILJET_SECRET=xxxxx
```
2. Add this file to .gitignore
3. Encrypt this file
```
$ gcloud kms encrypt \
    --location=global  \
    --keyring=my-key-ring \
    --key=my-key \
    --plaintext-file=export-secrets.sh \
    --ciphertext-file=export-secrets.sh.enc
```
4. Add decrypt step to the CI config
5. source export-secrets.sh

I'm going to prototype this with the MAILJET secrets and see how it goes.

**Comment by tmatsuo** [comment]
kms setup

1. enabled the Cloud KMS API on our project
2. created the key
```
$ gcloud config set project xxxxx
$ gcloud kms keyrings create ci --location global
$ gcloud kms keys create ci --location global --keyring ci --purpose encryption
```
3. created `testing/export-secrets.sh` that contains MAILJET secrets
4. added `export-secrets.sh` to `.gitignore`
5. encrypted the file
```
$ gcloud kms encrypt \
  --location global \
  --keyring=ci \
  --key=ci \
  --plaintext-file=testing/export-secrets.sh \
  --ciphertext-file=testing/export-secrets.sh.enc
```

**Comment by tmatsuo** [comment]
The dlp test is failing for PHP 7.2.
Let's add PHP 7.2 to the matrix, but allow failures for now.

**Comment by tmatsuo** [comment]
It's really a pain to maintain the composer.lock file for all the versions we support. Maybe we can just do `composer update` instead of `composer install`. For now, I only `composer update` on PHP 5.6.

**Comment by tmatsuo** [comment]
Still broken.

Maybe we should add the polyphil to php-tools and use it from there.

**Comment by tmatsuo** [comment]
Seems like pubsub/api is still using a very old version. We should update

```
PHP Fatal error:  Class 'DrSlump\Protobuf\Codec\PhpArray' not found in /home/[secure]/build/GoogleCloudPlatform/php-docs-samples/pubsub/api/vendor/google/cloud-core/PhpArray.php on line 32
```

**Comment by tmatsuo** [comment]
The spanner test is failing, fixing

**Comment by tmatsuo** [comment]
The spanner/test passed locally, so hopefully it will pass on travis too

**Comment by tmatsuo** [comment]
Still failing, this time speech fails:

```
1) Google\Cloud\Samples\Speech\Tests\speechTest::testTranscribe with data set #6 ('transcribe-stream', '/home/[secure]/build/GoogleClou...Hz.raw', 'LINEAR16', '32000')
strpos() expects parameter 1 to be string, array given
```

**Comment by tmatsuo** [comment]
Finally! We have a green test.

@SurferJeffAtGoogle Can you take a look?

**Comment by SurferJeffAtGoogle** [comment]
LGTM.

**Pull request merged**
