### PR TITLE
chore: Removing old datastore samples file

### PR DESCRIPTION
**Pull request by shivgautam**

### CODE REVIEW

**Comment by shivgautam** [comment]
The snippet-bot-check seems incorrect. The links on the pages that the bot checker mentions, refer to the new paths. So no region tags should be removed.

**Comment by shivgautam** [comment]
So a few auto-generated pages are still referring to the old sample file. This does not show up in the snippet-bot-check. I'll wait for those doc pages to be re-generated and then rerun the snippet bot checl

**Comment by shivgautam** [comment]
And, it's all set now. It can now be reviewed.

**Review by vishwarajanand — APPROVED** [review]
Lgtm, validated in logs that tests for Datastore are running.

**Pull request merged**
