### PR TITLE
Added semicolon at the end of the commented line with $path

### PR DESCRIPTION
**Pull request by wbadowski**

### CODE REVIEW

**Comment by wbadowski** [comment]
I signed it!

**Comment by tmatsuo** [comment]
@wbadowski Thanks, but I can not verify your CLA status yet. Did you signed with the same e-mail address which is used for your github account?

**Comment by wbadowski** [comment]
huh, I used different email, but I now updated my CLA contact info to include my github account name.

**Comment by tmatsuo** [comment]
The test is failing. It is because the vision test requires secrets to be present, and the secret is not available  for PRs coming from other repo. Now I'm merging this because the change is only for the comment section.

We'll address the test for PRs from other repo in #538

**Comment by tmatsuo** [comment]
@wbadowski Thanks!

**Pull request merged**
