### PR TITLE
BigTable Admin Samples

### PR DESCRIPTION
**Pull request by bshaffer**
Fixes tests for https://github.com/GoogleCloudPlatform/php-docs-samples/pull/743

### CODE REVIEW

**Comment by bshaffer** [comment]
@billyjacobson tests are passing - will you give this guy approval?

**Comment by bshaffer** [comment]
@juan-rael want to give this a quick look before I merge it?

**Comment by juan-rael** [comment]
I read it, its ok.

**Comment by billyjacobson** [comment]
@juan-rael I think you need to explicitly approve this for the CLA to pass

**Comment by juan-rael** [comment]
Theres are an extra file in the PR. Can you delete the file.txt?

**Comment by bshaffer** [comment]
@juan-rael done!

**Pull request merged**
