### PR TITLE
fix(spanner): skip failing backup test

### PR DESCRIPTION
**Pull request by larkee**
The ListBackupOperations test is failing across all the languages due to a bug in production. This PR marks that test as skipped to unblock other PRs. Once the bug is fixed, this skip can be removed.

Towards #1186

### CODE REVIEW

**Review by thiagotnunes — APPROVED** [review]
LGTM

**Comment by bshaffer** [comment]
I don't want to skip these tests without anything in place to ensure they get reinstated

Please file a bug at the very least to remind us to unskip them

**Comment by larkee** [comment]
@bshaffer I've created an issue for the test failure and assigned it to myself. I will keep it open until the test is unskipped and passing.

**Comment by skuruppu** [comment]
@bshaffer it could take weeks to do a backend rollout with a fix so I think we have no choice but to skip this for now. We're doing the same across all the language repos. @larkee will keep the issue open until we revert the skip. Hope that's ok with you.

**Review by bshaffer — APPROVED** [review]
We are keeping https://github.com/GoogleCloudPlatform/php-docs-samples/issues/1186 open to track this

**Pull request merged**
