### PR TITLE
Added integration tests for Cloud SQL

### PR DESCRIPTION
**Pull request by craiglabenz**

### CODE REVIEW

**Comment by tmatsuo** [comment]
@craiglabenz 

Re: snippet-bot comment

The bot thinks that if we merge this PR, it will break some of our devsite pages. Please fix it before merging.

**Review by bshaffer — CHANGES_REQUESTED** [review]
I have requested some refactorings where the environment variables are concerned. This will make the samples and tests more concise and readable.

**Review by craiglabenz — COMMENTED** [review]
Thanks for that review, @bshaffer. I've incorporated each recommended change.

**Review by bshaffer — CHANGES_REQUESTED** [review]
Please Revert your changes to `CONTRIBUTING.md` and to all three `VotesTest.php` files!

**Review by bshaffer — APPROVED** [review]

**Pull request merged**
