### PR TITLE
Made the datastore tests less flaky

### PR DESCRIPTION
**Pull request by tmatsuo**
TODO

- [x] Upgrade google/php-tools to 0.6.3

### CODE REVIEW

**Comment by bshaffer** [comment]
Personally, I'd be ok just hardcoding a number, or incrementing the default in https://github.com/GoogleCloudPlatform/php-tools

**Comment by tmatsuo** [comment]
@bshaffer 

I think the current default `3` in the tool is somewhat appropriate. I looked at the logs of the recent failures and realized that we should use separate namespace for each test setup, which will likely be sufficient for stabler test result.

Also, I'd like to have an easy way to experiment with the retry count once if the datastore tests become flaky.

**Comment by bshaffer** [comment]
We could still do better than this, i.e. have the Trait use a default static variable `eventuallyConsistentRetryCount` and then override it in the test classes. Passing it into every single call is not optimal.

**Comment by tmatsuo** [comment]
@bshaffer Yeah I tried that path first and I agree. https://github.com/GoogleCloudPlatform/php-tools/pull/19

**Comment by tmatsuo** [comment]
@bshaffer PTAL

**Comment by tmatsuo** [comment]
Running the tests on jenkins

**Comment by tmatsuo** [comment]
The tests on our jenkins are not green so far for several failure.
1) Datastore eventually consistency error
I hadn't set `DATASTORE_EVENTUALLY_CONSISTENT_RETRY_COUNT` when I saw this error, so I set it to 10.

2) Some 502 errors after flex deployment
Sigh, it is still happening. I raised `GOOGLE_DEPLOYMENT_DELAY` to 60.

**Comment by tmatsuo** [comment]
The tests on jenkins are still somewhat flaky, but the last build was green.
Kicked off the travis build, and I'll merge once it's green too.

**Pull request merged**
