### PR TITLE
[CloudAsset] Update client library version to use endpoint v1.

### PR DESCRIPTION
**Pull request by peter-zheng-g**

### CODE REVIEW

**Comment by peter-zheng-g** [comment]
The presubmit succeeded for php56, php70, and php71. It only failed for php72 due to some i/o timeout. Can some one please take a look?

**Comment by peter-zheng-g** [comment]
Can someone please help trigger the Kokoro CI? The presubmit passed for php56, php70, and php71, and only failed for php72, and it didn't seem related to my change and likely temporary. Thanks.

**Comment by peter-zheng-g** [comment]
Can someone please merge the pull request? Thanks!

**Comment by bshaffer** [comment]
Looks great, thanks!

**Pull request merged**
