### PR TITLE
Changed the directory structure.

### PR DESCRIPTION
**Pull request by tmatsuo**
Moved `managed_vms` -> `appengine/flexible` and `app_engine` to `appengine/standard`

### CODE REVIEW

**Comment by tmatsuo** [comment]
Now we're using `appengine`

**Comment by JustinBeckwith** [comment]
Thank you :) LGTM!  Please do a search in the docs in google3/googledata/devsite/site-cloud to make sure we're not referencing specific github paths here?  Guessing @bshaffer would know what specifically to look for.

**Comment by tmatsuo** [comment]
Yeah I'll take care of it

**Comment by bshaffer** [comment]
We will need to update our jenkins config as well

**Comment by tmatsuo** [comment]
already done :)

**Pull request merged**
