### PR TITLE
Update region tags for consistency

### PR DESCRIPTION
**Pull request by nnegrey**

### CODE REVIEW

**Comment by nnegrey** [comment]
Updated some more region tags. PTAL
Should be good to go now.

**Comment by nnegrey** [comment]
@bshaffer Any ideas why the tests might be failing?

**Comment by bshaffer** [comment]
The error states: `"Errors in 'fake_display_name_for_testing_...' entity: Name length is greater than 30 chars.",`

That seems pretty clear. Although I thought we fixed this already. But we just need to shorten the entity name length in the tests. Pretty awesome that Dialogflow decided to break BC like that.

**Comment by nnegrey** [comment]
@bshaffer Got it working

**Pull request merged**
