### PR TITLE
Add openapi-appengine.yaml file for App Engine deployments.

### PR DESCRIPTION
**Pull request by p-buse**
After conversation with the Endpoints team, this was the most effective solution we came up with to guide users through setting up Endpoints on App Engine. Having users uncomment code proved to be difficult. If you have another idea that could work better, please let me know. Otherwise, this will have to do.

### CODE REVIEW

**Comment by bshaffer** [comment]
Seems fine, but if `openapi-appengine.yaml` is for App Engine, what is `openapi.yaml` for? Is it for compute engine, container engine, etc.

**Comment by p-buse** [comment]
That's correct. GKE and GCE use the PROJECT-ID.cloud.goog host format, whereas App Engine uses PROJECT-ID.appspot.com.

**Comment by bshaffer** [comment]
This is LGTM, is there anything else needed before merge?

**Comment by p-buse** [comment]
Nope, this is ready to go.

**Pull request merged**
