### PR TITLE
Cleanup unused samples and affected code

### PR DESCRIPTION
**Pull request by Strykrol**
Removing PHP samples that aren't being surfaced to cloud.google.com. I made some best guesses on the corresponding test and configuration file adjustments to align with these deletions.

### CODE REVIEW

**Comment by bshaffer** [comment]
It seems unnecessary to remove working well-tested samples just because they're not in the docs. What is the justification for this?

**Comment by Strykrol** [comment]
It's part of a clean-up to reconcile samples to a state more catered around UX, whether that is by finding a sensible spot in docs or deleting the clutter from a samples repository where sample context isn't necessarily prevalent. I can provide the internal project link if you want to reach out beyond this PR.

FWIW the dialogflow-specific deletion decisions were signed off by @nnegrey who may have additional insight. Dialogflow sample deletions are occurring across all language/repos.

**Comment by bshaffer** [comment]
I'd rather just remove the region tags (to indicate these are not in docs) and leave the working samples alone. We can even flag them in the header as not being used in the docs so that we can remove them down the road if they cause issues, but because they're not requiring any maintenance cost and they're working and fully tested, I'd rather keep them around in case someone stumbles upon them and finds them useful

**Comment by Strykrol** [comment]
If you want to keep the code, then we might as well keep the region tags for _potential_ future use. I can close this PR with no changes performed.

**Pull request closed without merging**
