### PR TITLE
KMS: Make samples consistent across languages.

### PR DESCRIPTION
**Pull request by white0ut**
This change:

* Uses a consistent "id" suffix for resource name components.
* Uses ciphertext and plaintext instead of inFile and outFile.
* Correctly handles base64 decoding and encoding of responses.
	* Data written to files should never be base64 encoded.

Tracking bug: http://b/64758639

### CODE REVIEW

**Comment by bshaffer** [comment]
None of the tests have been updated to accommodate for these changes.

**Comment by white0ut** [comment]
Sorry about that. Tests updated

**Comment by white0ut** [comment]
Brent, I'm seeing failures related to ADC, is that because this is a fork?

```
Unable to read the credential file specified by  GOOGLE_APPLICATION_CREDENTIALS: file /home/travis/build/GoogleCloudPlatform/php-docs-samples/credentials.json does not exist
```

**Comment by bshaffer** [comment]
Yes, unfortunately these need to run on the same branch in order for travis to use the credentials.

I ran the tests locally and have found a lot of errors. I'll push a separate branch and fix the issues.

**Pull request closed without merging**
