### PR TITLE
adds Jenkins Build Status badge

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tmatsuo** [comment]
Do we need a test utility for eventual consistent stuff?
Something like this:
https://github.com/GoogleCloudPlatform/python-repo-tools/blob/master/gcp/testing/eventually_consistent.py

**Comment by bshaffer** [comment]
@tmatsuo I think that's a good idea

**Comment by tmatsuo** [comment]
@bshaffer 
Here is the prototype:
https://github.com/GoogleCloudPlatform/php-docs-samples/pull/181/files#diff-a05c516ac20f40279c1f18e7c3ea5166R457

**Comment by bshaffer** [comment]
I added https://github.com/GoogleCloudPlatform/php-tools/pull/15 for this, WDYT?

**Pull request merged**
