### PR TITLE
Adding phpmyadmin on App Engine Standard.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by tmatsuo** [comment]
Sorry updated with a minor cs fix

**Comment by bshaffer** [comment]
This seems pretty great. We should add a README though.

**Comment by tmatsuo** [comment]
Thanks, added the README. The preview is available at:
https://github.com/GoogleCloudPlatform/php-docs-samples/tree/phpmyadmin/app_engine/phpmyadmin

PTAL

**Comment by bshaffer** [comment]
LGTM

**Comment by tmatsuo** [comment]
Thanks I just squashed the commits. I will merge this shortly.

**Comment by bshaffer** [comment]
I do want to mention I'm not crazy about using twig to render all these files. It's a little overpowered for this use case, and I think it would be better to just have:

```php
$newContent = strtr([
   '%parameter1%' => $parameter1,
   '%parameter2%' => $parameter2,
   '%parameter3%' => $parameter3,
], file_get_contents($file));
```

**Pull request merged**
